import { lstatSync, mkdirSync, readFileSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const BASHRC_MARKER = "Generated by llm-pet install";

export const BASHRC_SNIPPET = `# ${BASHRC_MARKER}. Do not edit.
codex() { command llm-pet wrap codex "$@"; }
claude() { command llm-pet wrap claude "$@"; }
`;

export type InstallPaths = {
  bin: string;
  hook: string;
  shell: string;
};

function defaultHome(): string {
  return process.env.HOME?.trim() || os.homedir();
}

export function installTargets(
  repoRoot: string,
  home = defaultHome()
): { links: InstallPaths; sources: Omit<InstallPaths, "shell"> } {
  const dataHome = process.env.XDG_DATA_HOME?.trim() || path.join(home, ".local", "share");
  return {
    sources: {
      bin: path.join(repoRoot, "dist", "main.js"),
      hook: path.resolve(repoRoot, "..", "..", "hooks", "hook.cjs")
    },
    links: {
      bin: path.join(home, ".local", "bin", "llm-pet"),
      hook: path.join(dataHome, "llm-pets", "hook.cjs"),
      shell: path.join(home, ".bashrc.d", "llm-pets.sh")
    }
  };
}

function ours(target: string, repoRoot: string, hookSource?: string): boolean {
  try {
    const stat = lstatSync(target);
    if (stat.isSymbolicLink()) {
      const destination = readlinkSync(target);
      const resolved = path.resolve(path.dirname(target), destination);
      return resolved.startsWith(repoRoot + path.sep) || resolved === repoRoot || resolved === hookSource;
    }
    if (stat.isFile()) {
      const text = readFileSync(target, "utf8");
      return text.includes(BASHRC_MARKER) || text.includes("_llm_pet_start") || text.includes("LLM Pets hook");
    }
  } catch {
    return false;
  }
  return false;
}

function replaceable(target: string, repoRoot: string, hookSource?: string): boolean {
  try {
    const stat = lstatSync(target);
    if (stat.isSymbolicLink()) {
      return true;
    }
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "ENOENT";
  }
  return ours(target, repoRoot, hookSource);
}

function link(source: string, target: string, repoRoot: string, hookSource?: string): void {
  mkdirSync(path.dirname(target), { recursive: true });
  if (!replaceable(target, repoRoot, hookSource)) {
    throw new Error(`refusing to replace non-symlink: ${target}`);
  }
  rmSync(target, { force: true });
  symlinkSync(source, target);
  console.log(`  ${target} -> ${source}`);
}

function writeBashrc(target: string, repoRoot: string, hookSource?: string): void {
  mkdirSync(path.dirname(target), { recursive: true });
  if (!replaceable(target, repoRoot, hookSource)) {
    throw new Error(`refusing to replace non-symlink: ${target}`);
  }
  rmSync(target, { force: true });
  writeFileSync(target, BASHRC_SNIPPET);
  console.log(`  ${target} (wraps codex and claude)`);
}

export function install(options: { home?: string; repoRoot?: string } = {}): void {
  const repoRoot = options.repoRoot ?? path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const home = options.home ?? defaultHome();
  const { links, sources } = installTargets(repoRoot, home);
  console.log("Linking:");
  link(sources.bin, links.bin, repoRoot, sources.hook);
  link(sources.hook, links.hook, repoRoot, sources.hook);
  writeBashrc(links.shell, repoRoot, sources.hook);
  const hook = links.hook;
  console.log("");
  console.log("The wrapper merges hooks for the agent it launches:");
  console.log("");
  console.log("  Codex   ~/.codex/hooks.json");
  console.log("  Claude  ~/.claude/settings.json");
  console.log("");
  console.log(`Both run:  node ${hook}`);
  console.log("");
  console.log("Start codex or claude, then check the setup with:  llm-pet check");
}

export function uninstall(options: { home?: string; repoRoot?: string } = {}): void {
  const repoRoot = options.repoRoot ?? path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
  const home = options.home ?? defaultHome();
  const { links, sources } = installTargets(repoRoot, home);
  console.log("Removing links:");
  for (const target of Object.values(links)) {
    if (!ours(target, repoRoot, sources.hook)) {
      continue;
    }
    rmSync(target, { force: true });
    console.log(`  removed ${target}`);
  }
}
